### ISSUE TITLE
Add simple collision response

### ISSUE THREAD

**Issue by JoeStrout** [JoeStrout/miniscript-physics#1]
The current code detects collisions (tinting the sprites red) but does not do anything about it.  In particular, the `calcCollisions` method has a `// ToDo` comment where the collision response should be.

This is where we need to call a new function that calculates and applies the collision forces on the bodies.

This is a well-known problem; searching for "2d physics collision response" should turn up some algorithms.  Books such as [_Physics for Game Developers_](https://www.amazon.com/Physics-Game-Developers-David-Bourg/dp/0596000065) are also a great reference.

For this ticket, it's fine if the collision code only works for the simple case of single-Bounds physics bodies.  We can generalize it to more complex shapes later.

We'll know the code is working when the test program (`test.ms`) shows the two small blocks coming to rest on the ground, one probably on top of the other (perhaps at a jaunty angle).

**Comment by JoeStrout** [comment]
Note: there is a bounty on this issue at: https://app.bountysource.com/issues/123726693

**Comment by JoeStrout** [comment]
The above PR doesn't do it; (1) it's not valid MiniScript language, (2) it's declaring functions and such in the middle of an `if` block, and (3) even if it compiled and ran, it appears to be code that would at best work for circular physics bodies, not rectangular ones like ours.

So, this issue remains open for anyone who wants to tackle it!  (But please be sure to test your solution before submitting a PR.)

**Comment by pipe01** [comment]
Have you considered integrating an existing physics engine like Box2D into MiniMicro or Soda? A full-on physics engine requires a ton of calculations per second, not to mention the complexity of the code. I don't think it's feasible to implement something like Box2D in a scripting language like MiniScript, so in my opinion the best course of action would be to either integrate Box2D as mentioned or reduce the scope of this physics engine to a very simple one without e.g. torque and accurate simulation.

**Comment by JoeStrout** [comment]
Yes, of course I considered it.  It might be appropriate for Soda, but it's not really in keeping with Mini Micro's philosophy.  Also, I don't want the physics to be a black box — I want Mini Micro users to be able to look under the hood and poke around to learn how it works.

**Comment by pipe01** [comment]
Fair enough, that sounds good. In that case, can you take a look at the PR? I've added a few different scenarios to show off different features.

**Comment by JoeStrout** [comment]
Yeah sorry, I didn't keep up on my email this weekend and for some reason the notifications didn't come to Discord as expected.

I just had a quick skim through the code and it certainly looks good, but I won't have time to try it until this afternoon.  I'm looking forward to it!

**Comment by JoeStrout** [comment]
(PR is awesome, but doesn't completely close this issue as the blocks do not yet rotate and come to rest properly.  We still need to add torque for that to work.)

**Comment by makeasnek** [comment]
Please do not use bountysource. Many devs have had trouble getting paid there. You can check out this lemmy community as an alternative https://lemmy.ml/c/bugbounties

For statements from devs who have been unable to cash out from bountysource see:
https://github.com/bountysource/core/issues
